name: bpl_chatbot

channels:
  - conda-forge
  
dependencies:
  - python=3.12
  - pip=24.2

  # Core scientific python
  - numpy==1.26.4
  - pandas==2.2.3
  
  # Plotting
  - matplotlib==3.9.2

  # Spatial packages
  - rasterio==1.4.0
  - rioxarray==0.17.0
  - geopandas==1.0.1
  - shapely==2.0.6
  - rasterstats==0.20.0

  # Pytorch
  - pytorch==2.4.1

  # LangChain
  - pip:
    - langchain_ollama==0.2.0
    - langchain_core==0.3.9
    - langchain_community==0.3.1
    - langchain_experimental==0.3.2
    - langgraph

  # App
  - streamlit==1.39.0

  # Jupyter Environment
  - papermill
  - autopep8
  - jupyterlab
  - notebook
  - ipython
  # jupyter_contrib_nbextensions
  - nbclean
  - nbresuse



