name: crop_classifier

channel_priority: strict
channels:
  - conda-forge
  - defaults
  
dependencies:
  - python=3.12

  # Core packages
  - numpy
  - pandas
  - pyarrow
  
  # Plotting packages
  - matplotlib

  # Spatial packages
  - rioxarray
  - rasterio
  - geopandas
  - shapely

  # Modeling packages
  - scikit-learn
  - xgboost

  # Jupyter Environment
  - papermill
  - autopep8
  - jupyterlab
  - notebook
  - ipython
  - nbclean
  - nbresuse
